services:
  jenkins:
    build: .
    container_name: jenkins_container
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
volumes:
  jenkins_home: